services:
  tree_house.conan_statistico.listener.direct_response:
    class: TreeHouse\ConanStatisticoBundle\EventListener\DirectResponseListener
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 1024  }
